export enum Type {
  SERVICE_STATION = 'SERVICE_STATION',
  WASH_STATION = 'WASH_STATION',
  GAS_EQUIPMENT_STATION = 'GAS_EQUIPMENT_STATION',
  DETAILING = 'DETAILING',
  SHOP = 'SHOP',
  TIRE_STATION = 'TIRE_STATION'
}